### ISSUE TITLE
Enable Base64 decoding for googlesource.com

### ISSUE THREAD

**Issue by djkoloski** [mozilla/cargo-vet#394]
We host all of our code in gitiles, which doesn't provide a way to directly download individual files. You can however download files as base64 blobs by adding `?format=TEXT` to the URL. It would be great if we could specify this as an option in our import section, something like:

```toml
[imports.fuchsia]
url = "https://fuchsia.googlesource.com/supply-chain/audits.toml?format=TEXT"
decode = "base64"
```

Is this something that would be worth adding to cargo-vet?
