### ISSUE TITLE
Recording violations with non-binary audit criteria

### ISSUE THREAD

**Issue by djkoloski** [mozilla/cargo-vet#446]
On Fuchsia, we'd like to record crate audits for UB risk on a scale from 0 (no unsafe code) to 4 (hard to avoid UB). We have that set up like this:

```toml
[criteria.ub-risk-0]
description = "..."
implies = "ub-risk-1"

[criteria.ub-risk-1]
description = "..."
implies = "ub-risk-2"

[criteria.ub-risk-2]
description = "..."
implies = "ub-risk-3"

# ...
```

Which works well, we can record our audits by picking the strictest criteria that a crate satisfies. However, this makes it tricky to record violations:

```toml
# `foo` is ub-risk-2, which implies ub-risk-3 or more and NOT ub-risk-1 or less
[[audits.foo]]
criteria = "ub-risk-2"

[[audits.foo]]
violation = "ub-risk-1"

[[audits.foo]]
violation = "ub-risk-0"
```

Right now, it looks like we'll have to record violations at every lower `ub-risk-` level than the one we signed off on. Ideally, we'd be able to opt into contrapositivity with `implies`: "`ub-risk-0` implies `ub-risk-1`" also means that "not `ub-risk-1` implies not `ub-risk-0`". That would bring us down to needing a single extra violation, which would be easier to handle.

If we could do that, then it would also be helpful for us to record the violation along with the criteria like:

```toml
[[audits.foo]]
criteria = "ub-risk-2"
violation = "ub-risk-1"
```

**Comment by bholley** [comment]
Ah interesting. So the idea here is that cargo-vet should apply modus tollens on `implies` relationships, and generate implicit violations for implying criteria? That seems sensible: a `safe-to-run` violation should imply a `safe-to-deploy` violation as well. I honestly would have thought we did that already, though honestly we've never used violation much.

I imagine it should also be pretty straightforward to allow `criteria` and `violation` to exist in the same audit entry.

@mystor WDYT?

**Comment by djkoloski** [comment]
I did some testing and it seems that `safe-to-deploy` and `safe-to-run` already have a modus tollens relationship:

`first/supply-chain/audits.toml`

```toml
[[audits.byteorder]]
who = "David Koloski <djkoloski@gmail.com>"
criteria = "safe-to-run"
violation = "^1.4.3"
```

`second/Cargo.toml`

```toml
[package]
name = "second"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "=1.4.3"
```

`second/supply-chain/config.toml`

```toml
[imports.first]
url = "http://localhost:8000/supply-chain/audits.toml"

[policy.byteorder]
criteria = "safe-to-deploy"

[[exemptions.byteorder]]
version = "1.4.3"
criteria = "safe-to-deploy"
```

This yields the error we'd expect:

```
$ cargo vet check
Violations Found!
  byteorder:1.4.3
    the exemption 1.4.3
      criteria: ["safe-to-deploy"]
    conflicts with foreign (first) violation against ^1.4.3
      criteria: ["safe-to-run"]
      who: David Koloski <djkoloski@gmail.com>
```

However, swapping these for custom criteria:

`first/supply-chain/audits.toml`:

```toml
[criteria.safe-to-deploy-2]
description = "safe-to-deploy"
implies = "safe-to-run-2"

[criteria.safe-to-run-2]
description = "safe-to-run-2"

[[audits.byteorder]]
who = "David Koloski <djkoloski@gmail.com>"
criteria = "safe-to-run-2"
violation = "^1.4.3"
```

`second/supply-chain/audits.toml`:

```toml
[criteria.safe-to-deploy-2]
description = "safe-to-deploy"
implies = "safe-to-run-2"

[criteria.safe-to-run-2]
description = "safe-to-run-2"
```

`second/supply-chain/config.toml`:

```toml
[imports.first]
url = "http://localhost:8000/supply-chain/audits.toml"

[policy.byteorder]
criteria = "safe-to-deploy-2"

[[exemptions.byteorder]]
version = "1.4.3"
criteria = "safe-to-deploy-2"
```

Passes the check:

```
$ cargo vet check
Vetting Succeeded (1 exempted)
```

But also unexpectedly passes if the criteria is set to `safe-to-run-2` as well. Perhaps a bug? I'll try and minimize.

**Comment by mystor** [comment]
This error with `safe-to-deploy-2` and `safe-to-run-2` is happening because unlike the built-in criteria, custom criteria are not identity-mapped into the local namespace by default. You need to add a `[imports.first.criteria-map]` table mapping the criteria to local criteria in order to catch the relevant errors. Something like this could work:

```toml
[imports.first]
url = "http://localhost:8000/supply-chain/audits.toml"

[imports.first.criteria-map]
safe-to-deploy-2 = "safe-to-deploy-2"
safe-to-run-2 = "safe-to-run-2"
```

You can also use this to change how criteria are mapped for the default criteria, though there is an identity mapping by-default.

In terms of your original request around combining violations and audits into a single criteria, this would be potentially possible, but not the easiest to implement, as we currently always require only one key, and don't allow combo entries like this. If we did add something like that, it'd also be odd as the `violation` field for most violation entries is a `VersionReq` to specify a range of versions, rather than a criteria to add a violation for. Overloading the meaning like that feels a bit confusing.

It would be interesting to learn more about how you want to use violations for these ub criteria. Right now our story around violations is one of the weakest stories (as others haven't had a use for them yet, so they haven't been exercised much), and it'd be good to learn more about how people who want to use them expect them to act.
