### ISSUE TITLE
Override Global Default Policies

### ISSUE THREAD

**Issue by Folling** [mozilla/cargo-vet#493]
Is it possible to override the default policies?

If it isn't I suggest implementing it as follows:
```toml
[policy]
criteria = "..."
dev-criteria = "..."
build-criteria = "..."
```
Since it is otherwise quite tedious to manage this on a per-crate level.
